/** Portal UI strings (EN + AR), registered into the core string table (NFR localization, A-07). */
import { registerStrings } from '@medsim/core';

export const PORTAL_STRINGS: Record<string, { en: string; ar: string }> = {
  // navigation / shell
  'p.main_nav': { en: 'Main navigation', ar: 'التنقل الرئيسي' },
  'p.portal_subtitle': { en: 'Staff portal — authoring, review, sessions and reports', ar: 'بوابة الكادر — التأليف والمراجعة والجلسات والتقارير' },
  'p.forbidden': { en: 'You do not have permission to open this page.', ar: 'ليست لديك صلاحية لفتح هذه الصفحة.' },
  'p.admin': { en: 'Administration', ar: 'الإدارة' },
  'p.models': { en: 'Models', ar: 'النماذج' },
  'p.review_queue': { en: 'Review queue', ar: 'قائمة المراجعة' },
  'p.review': { en: 'Review', ar: 'مراجعة' },
  'p.sus_short': { en: 'Questionnaire', ar: 'الاستبيان' },
  'p.text_smaller': { en: 'Smaller text', ar: 'تصغير النص' },
  'p.text_larger': { en: 'Larger text', ar: 'تكبير النص' },
  'p.cb_palette_short': { en: 'CB-safe colours', ar: 'ألوان آمنة' },
  'p.home.cases': { en: 'Write and edit cases, preview them as a student and submit for review.', ar: 'اكتب الحالات وعدّلها، وعاينها كطالب، وأرسلها للمراجعة.' },
  'p.home.review': { en: 'Approve or reject cases and sign off model versions.', ar: 'وافق على الحالات أو ارفضها، واعتمد إصدارات النماذج.' },
  'p.home.sessions': { en: 'Create lab sessions and monitor stations live.', ar: 'أنشئ جلسات المختبر وراقب المحطات مباشرة.' },
  'p.home.reports': { en: 'Results, question analytics, heatmaps and exports.', ar: 'النتائج وتحليل الأسئلة والخرائط الحرارية والتصدير.' },
  'p.home.grading': { en: 'Grade free-text answers.', ar: 'صحّح الإجابات النصية الحرة.' },
  'p.home.admin': { en: 'Users, cohorts, courses and course packages.', ar: 'المستخدمون والدفعات والمقررات وحزم المقررات.' },
  'p.home.student': { en: 'Students take cases at a lab station. You can fill in the usability questionnaire here.', ar: 'يؤدي الطلاب الحالات في محطة المختبر. يمكنك تعبئة استبيان سهولة الاستخدام هنا.' },
  // generic
  'p.actions': { en: 'Actions', ar: 'الإجراءات' },
  'p.updated': { en: 'Updated', ar: 'آخر تحديث' },
  'p.version_col': { en: 'Version', ar: 'الإصدار' },
  'p.create': { en: 'Create', ar: 'إنشاء' },
  'p.name': { en: 'Name', ar: 'الاسم' },
  'p.code': { en: 'Code', ar: 'الرمز' },
  'p.year': { en: 'Year', ar: 'السنة' },
  'p.cohort': { en: 'Cohort', ar: 'الدفعة' },
  'p.notes': { en: 'Notes', ar: 'ملاحظات' },
  'p.upload': { en: 'Upload', ar: 'رفع' },
  'p.file': { en: 'File', ar: 'الملف' },
  'p.export': { en: 'Export', ar: 'تصدير' },
  'p.import': { en: 'Import', ar: 'استيراد' },
  'p.you': { en: 'you', ar: 'أنت' },
  'p.settings': { en: 'Settings', ar: 'الإعدادات' },
  'p.target': { en: 'Target', ar: 'الهدف' },
  // case list / editor
  'p.my_drafts': { en: 'My drafts', ar: 'مسوداتي' },
  'p.other_drafts': { en: 'Other drafts and archived', ar: 'مسودات أخرى ومؤرشفة' },
  'p.case_form': { en: 'Case authoring form', ar: 'نموذج تأليف الحالة' },
  'p.case_details': { en: 'Case details', ar: 'تفاصيل الحالة' },
  'p.case_id': { en: 'Case ID', ar: 'معرّف الحالة' },
  'p.topic': { en: 'Topic', ar: 'الموضوع' },
  'p.model_not_signed': { en: 'Model version not yet signed off', ar: 'لم يُعتمد إصدار النموذج بعد' },
  'p.camera_preset': { en: 'Camera preset', ar: 'وضع الكاميرا' },
  'p.camera.anterior': { en: 'Anterior', ar: 'أمامي' },
  'p.camera.posterior': { en: 'Posterior', ar: 'خلفي' },
  'p.camera.left': { en: 'Left', ar: 'أيسر' },
  'p.camera.right': { en: 'Right', ar: 'أيمن' },
  'p.camera.superior': { en: 'Superior', ar: 'علوي' },
  'p.camera.inferior': { en: 'Inferior', ar: 'سفلي' },
  'p.camera.custom': { en: 'Custom (captured)', ar: 'مخصص (ملتقط)' },
  'p.hidden_layers': { en: 'Layers hidden when the case opens', ar: 'الطبقات المخفية عند فتح الحالة' },
  'p.allowed_layers': { en: 'Layers the student may toggle', ar: 'الطبقات التي يمكن للطالب تبديلها' },
  'p.allowed_layers_hint': { en: 'none ticked = all', ar: 'عدم التحديد = الكل' },
  'p.labels_allowed': { en: 'Labels on (practice cases only; always off in assessment)', ar: 'التسميات مفعّلة (لحالات التدريب فقط؛ مطفأة دائماً في التقييم)' },
  'p.practice_case': { en: 'Practice case (not graded)', ar: 'حالة تدريب (غير محتسبة)' },
  'p.difficulty.easy': { en: 'Easy', ar: 'سهلة' },
  'p.difficulty.medium': { en: 'Medium', ar: 'متوسطة' },
  'p.difficulty.hard': { en: 'Hard', ar: 'صعبة' },
  'p.objectives': { en: 'Learning objectives', ar: 'أهداف التعلم' },
  'p.objectives_hint': { en: 'One objective per line', ar: 'هدف واحد في كل سطر' },
  'p.questions': { en: 'Questions', ar: 'الأسئلة' },
  'p.question_id': { en: 'ID', ar: 'المعرّف' },
  'p.question_type': { en: 'Type', ar: 'النوع' },
  'p.qtype.identify': { en: 'Identify on model', ar: 'التعرّف على النموذج' },
  'p.qtype.mcq': { en: 'Multiple choice', ar: 'اختيار من متعدد' },
  'p.qtype.multi': { en: 'Multi-select', ar: 'اختيار متعدد الإجابات' },
  'p.qtype.order': { en: 'Ordering', ar: 'ترتيب' },
  'p.qtype.text': { en: 'Free text', ar: 'نص حر' },
  'p.points': { en: 'Points', ar: 'الدرجات' },
  'p.tick_correct': { en: 'tick the correct option(s)', ar: 'حدّد الخيار/الخيارات الصحيحة' },
  'p.correct_option': { en: 'Option {key} is correct', ar: 'الخيار {key} صحيح' },
  'p.option_key': { en: 'Option key', ar: 'رمز الخيار' },
  'p.option_text': { en: 'Option text', ar: 'نص الخيار' },
  'p.add_option': { en: 'Add option', ar: 'إضافة خيار' },
  'p.remove_option': { en: 'Remove option', ar: 'حذف الخيار' },
  'p.partial_credit': { en: 'Award partial credit', ar: 'منح درجة جزئية' },
  'p.correct_order': { en: 'Correct order (option keys)', ar: 'الترتيب الصحيح (رموز الخيارات)' },
  'p.use_listed_order': { en: 'Use listed order', ar: 'استخدام الترتيب المدرج' },
  'p.identify_hint': { en: 'Structures accepted as correct. Click them on the model or pick from the list.', ar: 'البنى المقبولة كإجابة صحيحة. انقر عليها في النموذج أو اخترها من القائمة.' },
  'p.no_targets': { en: 'No target structures yet', ar: 'لا توجد بنى مستهدفة بعد' },
  'p.add_target': { en: 'Add structure', ar: 'إضافة بنية' },
  'p.remove_target': { en: 'Remove structure', ar: 'حذف البنية' },
  'p.match': { en: 'Scoring', ar: 'طريقة التصحيح' },
  'p.match.any': { en: 'Any listed structure is correct', ar: 'أي بنية مدرجة صحيحة' },
  'p.match.all': { en: 'All listed structures required', ar: 'يجب تحديد جميع البنى المدرجة' },
  'p.tag_on_model': { en: 'Tag on 3D model', ar: 'التحديد على النموذج ثلاثي الأبعاد' },
  'p.tagging_active': { en: 'Tagging on model…', ar: 'جارٍ التحديد على النموذج…' },
  'p.model_answer': { en: 'Model answer (for graders)', ar: 'الإجابة النموذجية (للمصححين)' },
  'p.manual_grading_note': { en: 'Free-text answers are graded manually.', ar: 'تُصحَّح الإجابات النصية يدوياً.' },
  'p.question_view': { en: 'Camera view for this question', ar: 'زاوية الكاميرا لهذا السؤال' },
  'p.case_default': { en: 'case initial view', ar: 'العرض الأولي للحالة' },
  'p.capture_for_question': { en: 'Capture current view for this question', ar: 'التقاط العرض الحالي لهذا السؤال' },
  'p.clear_view': { en: 'Clear view', ar: 'مسح العرض' },
  'p.visual_tagging': { en: '3D tagging', ar: 'التحديد ثلاثي الأبعاد' },
  'p.tagging_for': { en: 'Click structures to add/remove them as answers for question {id}. Rotate to the view you want, then capture it.', ar: 'انقر على البنى لإضافتها أو إزالتها كإجابات للسؤال {id}. دوّر النموذج إلى العرض المطلوب ثم التقطه.' },
  'p.tagging_none': { en: 'Add an "identify" question to tag answer structures. Rotate the model and capture the initial view.', ar: 'أضف سؤال "تعرّف" لتحديد بنى الإجابة. دوّر النموذج والتقط العرض الأولي.' },
  'p.no_view_yet': { en: 'Move the model first, then capture the view.', ar: 'حرّك النموذج أولاً ثم التقط العرض.' },
  'p.view_captured': { en: 'Camera view captured.', ar: 'تم التقاط زاوية الكاميرا.' },
  'p.err_course': { en: 'course: choose a course', ar: 'المقرر: اختر مقرراً' },
  'p.validate': { en: 'Check case', ar: 'فحص الحالة' },
  'p.valid': { en: 'The case is valid.', ar: 'الحالة صالحة.' },
  'p.saved_version': { en: 'Saved (version {n}).', ar: 'تم الحفظ (الإصدار {n}).' },
  'p.submitted_for_review': { en: 'Submitted for review.', ar: 'تم الإرسال للمراجعة.' },
  'p.locked_in_review': { en: 'This case is in review. Saving now withdraws it from review and creates a new draft version.', ar: 'هذه الحالة قيد المراجعة. الحفظ الآن يسحبها من المراجعة وينشئ إصدار مسودة جديداً.' },
  'p.published_new_version': { en: 'This case is published. Saving creates a new draft version; existing attempts stay linked to their version.', ar: 'هذه الحالة منشورة. الحفظ ينشئ إصدار مسودة جديداً، وتبقى المحاولات السابقة مرتبطة بإصدارها.' },
  'p.preview_note': { en: 'Student view: labels off, answer keys removed. Answers are not recorded.', ar: 'عرض الطالب: التسميات مطفأة ومفاتيح الإجابة محذوفة. لا تُسجَّل الإجابات.' },
  'p.model_version': { en: 'Model version', ar: 'إصدار النموذج' },
  // import
  'p.import_help': { en: 'Upload a filled-in case template (XLSX, or the two sheets as CSV). Each valid case is created as a draft.', ar: 'ارفع قالب الحالة بعد تعبئته (XLSX أو الورقتين بصيغة CSV). تُنشأ كل حالة صالحة كمسودة.' },
  'p.import_created': { en: '{count} case(s) created', ar: 'تم إنشاء {count} حالة/حالات' },
  'p.import_errors': { en: '{count} row error(s)', ar: '{count} خطأ/أخطاء في الصفوف' },
  'p.sheet': { en: 'Sheet', ar: 'الورقة' },
  'p.row': { en: 'Row', ar: 'الصف' },
  // review
  'p.case_with_keys': { en: 'Case content and answer keys', ar: 'محتوى الحالة ومفاتيح الإجابة' },
  'p.reject_needs_comment': { en: 'Please explain what needs to change before rejecting.', ar: 'يرجى توضيح ما يجب تغييره قبل الرفض.' },
  'p.cannot_review_own': { en: 'You authored this case — a different reviewer must approve it.', ar: 'أنت مؤلف هذه الحالة — يجب أن يوافق عليها مراجع آخر.' },
  'p.approved_msg': { en: 'Approved and published as version {n}.', ar: 'تمت الموافقة والنشر كالإصدار {n}.' },
  'p.rejected_msg': { en: 'Rejected — returned to the author as a draft.', ar: 'تم الرفض — أُعيدت إلى المؤلف كمسودة.' },
  'p.organ': { en: 'Organ', ar: 'العضو' },
  'p.structures': { en: 'Structures', ar: 'البنى' },
  'p.variants': { en: 'Variants', ar: 'الأنواع' },
  'p.sign_off': { en: 'Academic sign-off', ar: 'الاعتماد الأكاديمي' },
  'p.signed_by': { en: 'Signed off by {who} on {date}', ar: 'اعتمده {who} بتاريخ {date}' },
  'p.not_signed': { en: 'Not signed off', ar: 'غير معتمد' },
  'p.sign_off_action': { en: 'Sign off this version', ar: 'اعتماد هذا الإصدار' },
  'p.no_pathology': { en: 'This model has no pathological variant.', ar: 'لا يحتوي هذا النموذج على نوع مرضي.' },
  // sessions
  'p.session_name': { en: 'Session name', ar: 'اسم الجلسة' },
  'p.case_set': { en: 'Case set', ar: 'مجموعة الحالات' },
  'p.no_published': { en: 'No published cases yet', ar: 'لا توجد حالات منشورة بعد' },
  'p.create_session': { en: 'Create session', ar: 'إنشاء الجلسة' },
  'p.err_session_name': { en: 'Enter a session name', ar: 'أدخل اسم الجلسة' },
  'p.err_cohort': { en: 'Choose a cohort', ar: 'اختر دفعة' },
  'p.err_case_set': { en: 'Choose at least one case', ar: 'اختر حالة واحدة على الأقل' },
  'p.started': { en: 'Started', ar: 'بدأت' },
  'p.open_console': { en: 'Open console', ar: 'فتح لوحة المراقبة' },
  'p.session.scheduled': { en: 'Scheduled', ar: 'مجدولة' },
  'p.session.running': { en: 'Running', ar: 'جارية' },
  'p.session.stopped': { en: 'Stopped', ar: 'متوقفة' },
  'p.auto_refresh': { en: 'Updates every {n} s', ar: 'يتحدث كل {n} ثوانٍ' },
  'p.camera': { en: 'Camera', ar: 'الكاميرا' },
  'p.camera_ok': { en: 'OK', ar: 'تعمل' },
  'p.camera_fail': { en: 'Not available', ar: 'غير متاحة' },
  'p.last_seen': { en: 'Last seen', ar: 'آخر ظهور' },
  'p.locked': { en: 'Locked', ar: 'مقفلة' },
  'p.end_station_session': { en: 'End session on station', ar: 'إنهاء الجلسة على المحطة' },
  'p.command_queued': { en: 'Station {station}: "{cmd}" sent.', ar: 'المحطة {station}: تم إرسال "{cmd}".' },
  'p.cmd.set-input.fallback': { en: 'Switch to mouse', ar: 'التبديل إلى الفأرة' },
  'p.cmd.set-input.gesture': { en: 'Switch to gestures', ar: 'التبديل إلى الإيماءات' },
  'p.cmd.lock': { en: 'Lock', ar: 'قفل' },
  'p.cmd.unlock': { en: 'Unlock', ar: 'فتح' },
  'p.cmd.end-session': { en: 'End session', ar: 'إنهاء الجلسة' },
  'p.seconds_ago': { en: '{n} s ago', ar: 'قبل {n} ث' },
  'p.minutes_ago': { en: '{n} min ago', ar: 'قبل {n} د' },
  // reports
  'p.question_analytics': { en: 'Question analytics', ar: 'تحليل الأسئلة' },
  'p.success_metrics': { en: 'Success metrics', ar: 'مؤشرات النجاح' },
  'p.whole_course': { en: 'Whole course', ar: 'المقرر كاملاً' },
  'p.course_percent': { en: 'Course %', ar: 'نسبة المقرر' },
  'p.best_attempts_note': { en: 'Each cell: best score (number of attempts).', ar: 'كل خلية: أفضل درجة (عدد المحاولات).' },
  'p.structure': { en: 'Structure', ar: 'البنية' },
  'p.missed': { en: 'Missed as target', ar: 'لم يُتعرّف عليها كهدف' },
  'p.wrongly_selected': { en: 'Wrongly selected', ar: 'اختيرت خطأً' },
  'p.total_errors': { en: 'Total errors', ar: 'مجموع الأخطاء' },
  'p.as_target': { en: 'Times asked', ar: 'مرات السؤال' },
  'p.heat_scale': { en: 'Error count colour scale', ar: 'مقياس الألوان لعدد الأخطاء' },
  'p.show_on_model': { en: 'Show on 3D model', ar: 'العرض على النموذج ثلاثي الأبعاد' },
  'p.top_missed_highlighted': { en: 'The {n} most misidentified structures are highlighted.', ar: 'تم إبراز أكثر {n} بنى خطأً في التعرّف.' },
  'p.group_by': { en: 'Compare by', ar: 'المقارنة حسب' },
  'p.mean': { en: 'Mean', ar: 'المتوسط' },
  'p.median': { en: 'Median', ar: 'الوسيط' },
  'p.sd': { en: 'SD', ar: 'الانحراف المعياري' },
  'p.point_biserial': { en: 'Point-biserial', ar: 'الارتباط الثنائي النقطي' },
  'p.flags': { en: 'Flags', ar: 'تنبيهات' },
  'p.flag.too_hard': { en: 'Very hard (p < 0.2)', ar: 'صعب جداً (p < 0.2)' },
  'p.flag.too_easy': { en: 'Very easy (p > 0.9)', ar: 'سهل جداً (p > 0.9)' },
  'p.flag.low_discrimination': { en: 'Poor discrimination (D < 0.2)', ar: 'تمييز ضعيف (D < 0.2)' },
  'p.flag.negative_pb': { en: 'Negative point-biserial', ar: 'ارتباط ثنائي نقطي سالب' },
  'p.flag.low_pb': { en: 'Low point-biserial (< 0.2)', ar: 'ارتباط ثنائي نقطي منخفض (< 0.2)' },
  'p.item_help': { en: 'Difficulty = proportion correct. Discrimination = upper 27 % minus lower 27 % correct rate. Flagged items should be reviewed.', ar: 'الصعوبة = نسبة الإجابات الصحيحة. التمييز = نسبة الصحيح في أعلى 27٪ ناقص أدنى 27٪. ينبغي مراجعة الأسئلة المنبَّه عليها.' },
  'p.metric.completion': { en: 'Completion without proctor help', ar: 'الإكمال دون مساعدة المراقب' },
  'p.metric.fallback': { en: 'Fallback input usage', ar: 'استخدام الإدخال البديل' },
  'p.metric.time_to_publish': { en: 'Average time to publish a case', ar: 'متوسط زمن نشر الحالة' },
  'p.metric.active_authors': { en: 'Active authors', ar: 'المؤلفون النشطون' },
  'p.metric.sessions': { en: 'Sessions run', ar: 'الجلسات المنعقدة' },
  'p.metric.sus': { en: 'SUS mean', ar: 'متوسط SUS' },
  'p.metric.correlation': { en: 'Score ↔ written exam correlation (r)', ar: 'الارتباط بين الدرجة والامتحان التحريري (r)' },
  'p.exam_upload': { en: 'Upload written exam scores', ar: 'رفع درجات الامتحان التحريري' },
  'p.exam_help': { en: 'One line per student: student ID, percent.', ar: 'سطر لكل طالب: معرّف الطالب، النسبة المئوية.' },
  'p.exam_none': { en: 'No valid rows found.', ar: 'لم يتم العثور على صفوف صالحة.' },
  'p.exam_uploaded': { en: '{n} exam score(s) uploaded.', ar: 'تم رفع {n} درجة/درجات.' },
  // grading
  'p.response': { en: 'Response', ar: 'الإجابة' },
  'p.err_points': { en: 'Enter points (0 or more).', ar: 'أدخل الدرجة (0 أو أكثر).' },
  'p.graded_now': { en: 'Graded in this session', ar: 'تم تصحيحها في هذه الجلسة' },
  // admin
  'p.new_user': { en: 'New user', ar: 'مستخدم جديد' },
  'p.display_name': { en: 'Display name', ar: 'الاسم المعروض' },
  'p.roles': { en: 'Roles', ar: 'الأدوار' },
  'p.err_user_fields': { en: 'Username, password, display name and at least one role are required.', ar: 'اسم المستخدم وكلمة المرور والاسم المعروض ودور واحد على الأقل مطلوبة.' },
  'p.user_created': { en: 'User {name} created.', ar: 'تم إنشاء المستخدم {name}.' },
  'p.err_cohort_fields': { en: 'Enter a cohort name and year.', ar: 'أدخل اسم الدفعة والسنة.' },
  'p.err_course_fields': { en: 'Enter a course code and name.', ar: 'أدخل رمز المقرر واسمه.' },
  'p.enrolled': { en: '{cohort} enrolled in {course}.', ar: 'تم تسجيل {cohort} في {course}.' },
  'p.packages': { en: 'Course packages', ar: 'حزم المقررات' },
  'p.export_package': { en: 'Export a course package', ar: 'تصدير حزمة مقرر' },
  'p.import_package': { en: 'Import a course package', ar: 'استيراد حزمة مقرر' },
  'p.import_xlsx': { en: 'Workbook (.xlsx)', ar: 'مصنف (.xlsx)' },
  'p.import_or_csv': { en: 'or two CSV files', ar: 'أو ملفا CSV' },
  'p.cases_csv': { en: 'Cases sheet (.csv)', ar: 'ورقة الحالات (.csv)' },
  'p.questions_csv': { en: 'Questions sheet (.csv)', ar: 'ورقة الأسئلة (.csv)' },
  'p.enrolled_cohorts': { en: 'Enrolled cohorts', ar: 'الدفعات المسجلة' },
  'p.package_errors': { en: 'Some items could not be imported:', ar: 'تعذّر استيراد بعض العناصر:' },
  'p.err_not_package': { en: 'This file is not a MedSim course package.', ar: 'هذا الملف ليس حزمة مقرر ميدسيم.' },
  'p.package_imported': { en: 'Imported course {course} with {n} case(s).', ar: 'تم استيراد المقرر {course} مع {n} حالة/حالات.' },
  'p.organisations': { en: 'Organisations', ar: 'المؤسسات' },
  'p.err_org_fields': { en: 'Enter an organisation name.', ar: 'أدخل اسم المؤسسة.' },
  // SUS
  'p.sus_intro': { en: 'Please rate each statement about MedSim Lab from 1 (strongly disagree) to 5 (strongly agree).', ar: 'يرجى تقييم كل عبارة عن مختبر ميدسيم من 1 (لا أوافق بشدة) إلى 5 (أوافق بشدة).' },
  'p.sus_answer_all': { en: '{n} statement(s) left to answer', ar: 'تبقّى {n} عبارة/عبارات دون إجابة' },
  'p.sus_score': { en: 'Your SUS score: {score}', ar: 'درجة SUS الخاصة بك: {score}' },
};

registerStrings(PORTAL_STRINGS);
