import type { Lang, LocalizedText } from './types.js';

/** Resolve bilingual text, falling back to English. */
export function t(text: LocalizedText | undefined, lang: Lang): string {
  if (text === undefined || text === null) return '';
  if (typeof text === 'string') return text;
  if (lang === 'ar' && text.ar) return text.ar;
  return text.en ?? '';
}

export function isRtl(lang: Lang): boolean {
  return lang === 'ar';
}

/** UI string table keyed by id, EN and AR (NFR localization). */
export const UI_STRINGS: Record<string, { en: string; ar: string }> = {
  // --- general / navigation
  'app.title': { en: 'MedSim Lab', ar: 'مختبر ميدسيم' },
  next: { en: 'Next', ar: 'التالي' },
  previous: { en: 'Previous', ar: 'السابق' },
  back: { en: 'Back', ar: 'رجوع' },
  confirm: { en: 'Confirm', ar: 'تأكيد' },
  cancel: { en: 'Cancel', ar: 'إلغاء' },
  submit: { en: 'Submit', ar: 'إرسال' },
  save: { en: 'Save', ar: 'حفظ' },
  delete: { en: 'Delete', ar: 'حذف' },
  edit: { en: 'Edit', ar: 'تعديل' },
  close: { en: 'Close', ar: 'إغلاق' },
  start: { en: 'Start', ar: 'ابدأ' },
  stop: { en: 'Stop', ar: 'إيقاف' },
  continue: { en: 'Continue', ar: 'متابعة' },
  retry: { en: 'Retry', ar: 'إعادة المحاولة' },
  yes: { en: 'Yes', ar: 'نعم' },
  no: { en: 'No', ar: 'لا' },
  ok: { en: 'OK', ar: 'موافق' },
  loading: { en: 'Loading…', ar: 'جارٍ التحميل…' },
  error: { en: 'Error', ar: 'خطأ' },
  search: { en: 'Search', ar: 'بحث' },
  language: { en: 'Language', ar: 'اللغة' },
  'lang.en': { en: 'English', ar: 'الإنجليزية' },
  'lang.ar': { en: 'Arabic', ar: 'العربية' },
  settings: { en: 'Settings', ar: 'الإعدادات' },
  help: { en: 'Help', ar: 'مساعدة' },
  'text_size': { en: 'Text size', ar: 'حجم النص' },
  'high_contrast': { en: 'Colour-blind safe palette', ar: 'ألوان آمنة لعمى الألوان' },
  // --- viewer
  reset_view: { en: 'Reset view', ar: 'إعادة ضبط العرض' },
  labels: { en: 'Labels', ar: 'التسميات' },
  'labels.show': { en: 'Show labels', ar: 'إظهار التسميات' },
  'labels.hide': { en: 'Hide labels', ar: 'إخفاء التسميات' },
  'labels.disabled': { en: 'Labels are disabled during assessment', ar: 'التسميات معطلة أثناء التقييم' },
  layers: { en: 'Layers', ar: 'الطبقات' },
  'layer.show': { en: 'Show layer', ar: 'إظهار الطبقة' },
  'layer.hide': { en: 'Hide layer', ar: 'إخفاء الطبقة' },
  isolate: { en: 'Isolate', ar: 'عزل' },
  unisolate: { en: 'Show all', ar: 'إظهار الكل' },
  rotate: { en: 'Rotate', ar: 'تدوير' },
  zoom_in: { en: 'Zoom in', ar: 'تكبير' },
  zoom_out: { en: 'Zoom out', ar: 'تصغير' },
  pan: { en: 'Pan', ar: 'تحريك' },
  cross_section: { en: 'Cross-section', ar: 'مقطع عرضي' },
  'axis.x': { en: 'X axis', ar: 'المحور س' },
  'axis.y': { en: 'Y axis', ar: 'المحور ص' },
  'axis.z': { en: 'Z axis', ar: 'المحور ع' },
  animation: { en: 'Animation', ar: 'الحركة' },
  play: { en: 'Play', ar: 'تشغيل' },
  pause: { en: 'Pause', ar: 'إيقاف مؤقت' },
  compare: { en: 'Compare with normal', ar: 'مقارنة بالطبيعي' },
  normal: { en: 'Normal', ar: 'طبيعي' },
  pathological: { en: 'Pathological', ar: 'مرضي' },
  selected: { en: 'Selected: {name}', ar: 'المحدد: {name}' },
  nothing_selected: { en: 'Nothing selected', ar: 'لم يتم تحديد شيء' },
  parallax: { en: 'Head-tracked parallax (experimental)', ar: 'المنظور بتتبع الرأس (تجريبي)' },
  // --- station / case flow
  case: { en: 'Case', ar: 'الحالة' },
  question: { en: 'Question', ar: 'السؤال' },
  question_of: { en: 'Question {n} of {total}', ar: 'السؤال {n} من {total}' },
  points: { en: '{points} pts', ar: '{points} درجة' },
  time_remaining: { en: 'Time remaining', ar: 'الوقت المتبقي' },
  time_up: { en: 'Time is up — your answers were submitted', ar: 'انتهى الوقت — تم إرسال إجاباتك' },
  confirm_answer: { en: 'Confirm your answer?', ar: 'هل تؤكد إجابتك؟' },
  answer_recorded: { en: 'Answer recorded', ar: 'تم تسجيل الإجابة' },
  answer_cancelled: { en: 'Answer cancelled', ar: 'تم إلغاء الإجابة' },
  not_answered: { en: 'Not answered', ar: 'لم تتم الإجابة' },
  answered: { en: 'Answered', ar: 'تمت الإجابة' },
  select_structure: { en: 'Select a structure on the model', ar: 'اختر بنية على النموذج' },
  select_option: { en: 'Select an option', ar: 'اختر خياراً' },
  select_all_apply: { en: 'Select all that apply', ar: 'اختر كل ما ينطبق' },
  order_items: { en: 'Put the items in the correct order', ar: 'رتب العناصر بالترتيب الصحيح' },
  move_up: { en: 'Move up', ar: 'تحريك لأعلى' },
  move_down: { en: 'Move down', ar: 'تحريك لأسفل' },
  type_answer: { en: 'Type your answer', ar: 'اكتب إجابتك' },
  submit_case: { en: 'Submit case', ar: 'إرسال الحالة' },
  submit_confirm: { en: 'Submit all answers? You cannot change them afterwards.', ar: 'هل تريد إرسال جميع الإجابات؟ لا يمكنك تغييرها بعد ذلك.' },
  unanswered_warning: { en: '{count} question(s) not answered', ar: '{count} سؤال/أسئلة بدون إجابة' },
  submitted: { en: 'Submitted', ar: 'تم الإرسال' },
  score_summary: { en: 'Score summary', ar: 'ملخص الدرجات' },
  your_score: { en: 'Your score: {score} / {max} ({percent}%)', ar: 'درجتك: {score} / {max} ({percent}٪)' },
  score_hidden: { en: 'Your answers were submitted. Results will be released by your instructor.', ar: 'تم إرسال إجاباتك. سيعلن المدرس النتائج لاحقاً.' },
  correct: { en: 'Correct', ar: 'صحيح' },
  incorrect: { en: 'Incorrect', ar: 'خطأ' },
  correct_answer: { en: 'Correct answer', ar: 'الإجابة الصحيحة' },
  your_answer: { en: 'Your answer', ar: 'إجابتك' },
  feedback: { en: 'Feedback', ar: 'التغذية الراجعة' },
  pending_grading: { en: 'Awaiting manual grading', ar: 'بانتظار التصحيح اليدوي' },
  finish: { en: 'Finish', ar: 'إنهاء' },
  practice_mode: { en: 'Practice mode', ar: 'وضع التدريب' },
  practice_note: { en: 'Practice — not graded', ar: 'تدريب — غير محتسب' },
  start_practice: { en: 'Start practice', ar: 'ابدأ التدريب' },
  skip_practice: { en: 'Skip practice', ar: 'تخطي التدريب' },
  start_case: { en: 'Start case', ar: 'ابدأ الحالة' },
  choose_case: { en: 'Choose a case', ar: 'اختر حالة' },
  waiting_for_session: { en: 'Waiting for the proctor to start the session', ar: 'بانتظار بدء الجلسة من قبل المراقب' },
  station_locked: { en: 'This station is locked by the proctor', ar: 'هذه المحطة مقفلة من قبل المراقب' },
  offline: { en: 'Offline — answers will sync when the connection returns', ar: 'غير متصل — ستتم مزامنة الإجابات عند عودة الاتصال' },
  synced: { en: 'All results synced', ar: 'تمت مزامنة جميع النتائج' },
  pending_sync: { en: '{count} result(s) waiting to sync', ar: '{count} نتيجة/نتائج بانتظار المزامنة' },
  // --- hand tracking / input
  hand_lost: { en: 'Hand lost — raise your hand into view', ar: 'فُقدت اليد — ارفع يدك أمام الكاميرا' },
  hand_tracking: { en: 'Hand tracking', ar: 'تتبع اليد' },
  tracking_ok: { en: 'Tracking', ar: 'التتبع يعمل' },
  tracking_off: { en: 'Not tracking', ar: 'التتبع متوقف' },
  camera_unavailable: { en: 'Camera unavailable — using mouse and keyboard', ar: 'الكاميرا غير متاحة — يتم استخدام الفأرة ولوحة المفاتيح' },
  input_mode: { en: 'Input mode', ar: 'طريقة الإدخال' },
  'input.gesture': { en: 'Hand gestures', ar: 'إيماءات اليد' },
  'input.fallback': { en: 'Mouse / keyboard / touch', ar: 'الفأرة / لوحة المفاتيح / اللمس' },
  switch_to_mouse: { en: 'Switch to mouse', ar: 'التبديل إلى الفأرة' },
  switch_to_gestures: { en: 'Switch to gestures', ar: 'التبديل إلى الإيماءات' },
  primary_hand: { en: 'Primary hand', ar: 'اليد الأساسية' },
  'hand.left': { en: 'Left', ar: 'اليسرى' },
  'hand.right': { en: 'Right', ar: 'اليمنى' },
  'gesture.point': { en: 'Move your index finger to point', ar: 'حرّك إصبع السبابة للإشارة' },
  'gesture.pinch': { en: 'Pinch thumb and index to select', ar: 'اضغط الإبهام والسبابة معاً للاختيار' },
  'gesture.drag': { en: 'Pinch and drag to rotate', ar: 'اضغط واسحب للتدوير' },
  'gesture.zoom': { en: 'Pinch with both hands and move apart to zoom', ar: 'اضغط بكلتا اليدين وباعد بينهما للتكبير' },
  'gesture.reset': { en: 'Hold an open palm to reset the view', ar: 'افتح كفك وثبّتها لإعادة ضبط العرض' },
  // --- calibration
  calibration: { en: 'Calibration', ar: 'المعايرة' },
  'calibration.intro': { en: 'Let’s set up hand tracking for your reach', ar: 'لنقم بضبط تتبع اليد حسب مدى وصولك' },
  'calibration.step': { en: 'Step {n} of {total}', ar: 'الخطوة {n} من {total}' },
  'calibration.raise_hand': { en: 'Raise your hand so the camera can see it', ar: 'ارفع يدك لتراها الكاميرا' },
  'calibration.top_left': { en: 'Point to the top-left target and pinch', ar: 'أشر إلى الهدف في الأعلى يساراً واضغط' },
  'calibration.top_right': { en: 'Point to the top-right target and pinch', ar: 'أشر إلى الهدف في الأعلى يميناً واضغط' },
  'calibration.bottom_right': { en: 'Point to the bottom-right target and pinch', ar: 'أشر إلى الهدف في الأسفل يميناً واضغط' },
  'calibration.bottom_left': { en: 'Point to the bottom-left target and pinch', ar: 'أشر إلى الهدف في الأسفل يساراً واضغط' },
  'calibration.center': { en: 'Point to the centre target and pinch', ar: 'أشر إلى الهدف في المنتصف واضغط' },
  'calibration.done': { en: 'Calibration complete', ar: 'اكتملت المعايرة' },
  'calibration.failed': { en: 'Calibration failed — please try again', ar: 'فشلت المعايرة — يرجى المحاولة مرة أخرى' },
  'calibration.recalibrate': { en: 'Recalibrate', ar: 'إعادة المعايرة' },
  // --- kiosk
  proctor_pin: { en: 'Proctor PIN', ar: 'الرقم السري للمراقب' },
  exit_kiosk: { en: 'Exit kiosk mode', ar: 'الخروج من وضع الكشك' },
  wrong_pin: { en: 'Incorrect PIN', ar: 'رقم سري غير صحيح' },
  // --- portal / auth
  login: { en: 'Log in', ar: 'تسجيل الدخول' },
  logout: { en: 'Log out', ar: 'تسجيل الخروج' },
  username: { en: 'Username', ar: 'اسم المستخدم' },
  password: { en: 'Password', ar: 'كلمة المرور' },
  login_failed: { en: 'Invalid username or password', ar: 'اسم المستخدم أو كلمة المرور غير صحيحة' },
  welcome: { en: 'Welcome, {name}', ar: 'مرحباً، {name}' },
  dashboard: { en: 'Dashboard', ar: 'لوحة التحكم' },
  'role.student': { en: 'Student', ar: 'طالب' },
  'role.author': { en: 'Author', ar: 'مؤلف' },
  'role.reviewer': { en: 'Reviewer', ar: 'مراجع' },
  'role.proctor': { en: 'Proctor', ar: 'مراقب' },
  'role.admin': { en: 'Administrator', ar: 'مسؤول' },
  'role.superadmin': { en: 'Super administrator', ar: 'المسؤول الأعلى' },
  users: { en: 'Users', ar: 'المستخدمون' },
  cohorts: { en: 'Cohorts', ar: 'الدفعات' },
  courses: { en: 'Courses', ar: 'المقررات' },
  course: { en: 'Course', ar: 'المقرر' },
  enrol: { en: 'Enrol', ar: 'تسجيل' },
  cases: { en: 'Cases', ar: 'الحالات' },
  new_case: { en: 'New case', ar: 'حالة جديدة' },
  import_spreadsheet: { en: 'Import spreadsheet', ar: 'استيراد جدول بيانات' },
  download_template: { en: 'Download template', ar: 'تنزيل القالب' },
  preview: { en: 'Preview as student', ar: 'معاينة كطالب' },
  model: { en: 'Model', ar: 'النموذج' },
  variant: { en: 'Variant', ar: 'النوع' },
  stem: { en: 'Case stem', ar: 'نص الحالة' },
  prompt: { en: 'Prompt', ar: 'نص السؤال' },
  options: { en: 'Options', ar: 'الخيارات' },
  answer_key: { en: 'Answer key', ar: 'مفتاح الإجابة' },
  add_question: { en: 'Add question', ar: 'إضافة سؤال' },
  remove_question: { en: 'Remove question', ar: 'حذف السؤال' },
  initial_view: { en: 'Initial view', ar: 'العرض الأولي' },
  capture_view: { en: 'Capture current view', ar: 'التقاط العرض الحالي' },
  time_limit: { en: 'Time limit (minutes)', ar: 'المدة الزمنية (بالدقائق)' },
  feedback_level: { en: 'Feedback level', ar: 'مستوى التغذية الراجعة' },
  'feedback.none': { en: 'None', ar: 'بدون' },
  'feedback.score': { en: 'Score only', ar: 'الدرجة فقط' },
  'feedback.full': { en: 'Full', ar: 'كاملة' },
  status: { en: 'Status', ar: 'الحالة' },
  'status.draft': { en: 'Draft', ar: 'مسودة' },
  'status.in_review': { en: 'In review', ar: 'قيد المراجعة' },
  'status.published': { en: 'Published', ar: 'منشورة' },
  'status.archived': { en: 'Archived', ar: 'مؤرشفة' },
  submit_for_review: { en: 'Submit for review', ar: 'إرسال للمراجعة' },
  approve: { en: 'Approve', ar: 'موافقة' },
  reject: { en: 'Reject', ar: 'رفض' },
  review_comment: { en: 'Review comment', ar: 'تعليق المراجعة' },
  version: { en: 'Version {n}', ar: 'الإصدار {n}' },
  versions: { en: 'Versions', ar: 'الإصدارات' },
  sessions: { en: 'Sessions', ar: 'الجلسات' },
  new_session: { en: 'New session', ar: 'جلسة جديدة' },
  start_session: { en: 'Start session', ar: 'بدء الجلسة' },
  stop_session: { en: 'Stop session', ar: 'إيقاف الجلسة' },
  stations: { en: 'Stations', ar: 'المحطات' },
  station: { en: 'Station {id}', ar: 'المحطة {id}' },
  lock_station: { en: 'Lock station', ar: 'قفل المحطة' },
  unlock_station: { en: 'Unlock station', ar: 'فتح المحطة' },
  'station.idle': { en: 'Idle', ar: 'خاملة' },
  'station.calibrating': { en: 'Calibrating', ar: 'قيد المعايرة' },
  'station.practice': { en: 'Practice', ar: 'تدريب' },
  'station.in_progress': { en: 'In progress', ar: 'قيد التنفيذ' },
  'station.submitted': { en: 'Submitted', ar: 'تم الإرسال' },
  'station.offline': { en: 'Offline', ar: 'غير متصلة' },
  reports: { en: 'Reports', ar: 'التقارير' },
  results: { en: 'Results', ar: 'النتائج' },
  student: { en: 'Student', ar: 'الطالب' },
  attempts: { en: 'Attempts', ar: 'المحاولات' },
  correct_rate: { en: 'Correct rate', ar: 'نسبة الإجابات الصحيحة' },
  avg_time: { en: 'Average time', ar: 'متوسط الوقت' },
  common_wrong: { en: 'Most common wrong answer', ar: 'الإجابة الخاطئة الأكثر شيوعاً' },
  heatmap: { en: 'Structure heatmap', ar: 'خريطة حرارية للبنى' },
  item_analysis: { en: 'Item analysis', ar: 'تحليل الأسئلة' },
  difficulty: { en: 'Difficulty', ar: 'الصعوبة' },
  discrimination: { en: 'Discrimination', ar: 'التمييز' },
  cohort_comparison: { en: 'Cohort comparison', ar: 'مقارنة الدفعات' },
  export_csv: { en: 'Export CSV', ar: 'تصدير CSV' },
  export_pdf: { en: 'Export PDF', ar: 'تصدير PDF' },
  grading: { en: 'Manual grading', ar: 'التصحيح اليدوي' },
  grade: { en: 'Grade', ar: 'الدرجة' },
  no_data: { en: 'No data yet', ar: 'لا توجد بيانات بعد' },
  sus_title: { en: 'Usability questionnaire', ar: 'استبيان سهولة الاستخدام' },
  'sus.disagree': { en: 'Strongly disagree', ar: 'لا أوافق بشدة' },
  'sus.agree': { en: 'Strongly agree', ar: 'أوافق بشدة' },
  thank_you: { en: 'Thank you!', ar: 'شكراً لك!' },
};

/** Register additional UI strings (e.g. app-specific). Later registrations override earlier ones. */
export function registerStrings(table: Record<string, { en: string; ar: string }>): void {
  for (const [k, v] of Object.entries(table)) UI_STRINGS[k] = v;
}

export function ui(key: string, lang: Lang, vars?: Record<string, string | number>): string {
  const entry = UI_STRINGS[key];
  let s = entry ? (lang === 'ar' && entry.ar ? entry.ar : entry.en || key) : key;
  if (vars) s = s.replace(/\{(\w+)\}/g, (m, name: string) => (name in vars ? String(vars[name]) : m));
  return s;
}
