import { useState } from 'react';
import { Link } from 'react-router-dom';
import type { CaseRecord, Course } from '@medsim/core';
import type { ConversionError } from '@medsim/core/spreadsheet';
import { api } from '../../shared/api';
import { usePrefs } from '../../shared/prefs';
import { errorList, useApi } from '../hooks';
import { ErrorBox } from '../ui';

/** Template served by the lab server (generated by core into content/templates/). */
export const TEMPLATE_URL = '/api/templates/case-template.xlsx';

/** Spreadsheet import (A-01 via the portal): POST /api/cases/import multipart. */
export function ImportCases() {
  const { s } = usePrefs();
  const courses = useApi<Course[]>('/courses');
  const [courseId, setCourseId] = useState('');
  const [file, setFile] = useState<File | null>(null);
  const [busy, setBusy] = useState(false);
  const [errors, setErrors] = useState<string[]>([]);
  const [result, setResult] = useState<{ created: CaseRecord[]; errors: ConversionError[] } | null>(null);
  const course = courseId || courses.data?.[0]?.id || '';

  const upload = async () => {
    if (!file || !course) return;
    const fd = new FormData();
    fd.append('course_id', course);
    fd.append('file', file, file.name);
    setBusy(true); setErrors([]); setResult(null);
    try {
      setResult(await api<{ created: CaseRecord[]; errors: ConversionError[] }>('/cases/import', { method: 'POST', body: fd }));
    } catch (e) {
      setErrors(errorList(e));
    } finally {
      setBusy(false);
    }
  };

  return (
    <div>
      <h1>{s('import_spreadsheet')}</h1>
      <section className="card">
        <p>{s('p.import_help')}</p>
        <p><a href={TEMPLATE_URL} download="case-template.xlsx" data-testid="template-link">{s('download_template')}</a></p>
        <div className="row">
          <label>{s('course')}{' '}
            <select data-testid="import-course" value={course} onChange={(e) => setCourseId(e.target.value)}>
              {(courses.data ?? []).map((c) => <option key={c.id} value={c.id}>{c.code} — {c.name}</option>)}
            </select>
          </label>
          <label>{s('p.file')}{' '}
            <input type="file" data-testid="import-file" accept=".xlsx,.csv,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet,text/csv" onChange={(e) => setFile(e.target.files?.[0] ?? null)} />
          </label>
          <button type="button" className="primary" data-testid="import-upload" disabled={!file || !course || busy} onClick={() => void upload()}>{s('p.upload')}</button>
        </div>
      </section>
      <ErrorBox errors={errors} />
      {result && (
        <section className="card" data-testid="import-result">
          <h2>{s('p.import_created', { count: result.created.length })}</h2>
          <ul>{result.created.map((c) => <li key={c.id}><Link to={`/portal/cases/${encodeURIComponent(c.id)}/edit`}>{c.id}</Link> (v{c.version})</li>)}</ul>
          {result.errors.length > 0 && (
            <>
              <h2 className="error">{s('p.import_errors', { count: result.errors.length })}</h2>
              <table>
                <thead><tr><th>{s('p.sheet')}</th><th>{s('p.row')}</th><th>{s('case')}</th><th>{s('error')}</th></tr></thead>
                <tbody>{result.errors.map((e, i) => <tr key={i}><td>{e.sheet}</td><td>{e.row}</td><td>{e.case_id ?? ''}</td><td>{e.message}</td></tr>)}</tbody>
              </table>
            </>
          )}
        </section>
      )}
    </div>
  );
}
